### ISSUE TITLE
Sharing of pretrained model weights?

### ISSUE THREAD

**Issue by xiankgx** [rmokady/CLIP_prefix_caption#10]
Hi, I'm thinking if you can share the pretrained model weights so it is easier to try it out without first having to train our own models?

**Comment by xiankgx** [comment]
Sorry, I saw you actually have the pretrained models in your inference notebook, but it would be cool if you could share the link perhaps in your README.md.

**Comment by rmokady** [comment]
@xiankgx 
Thanks for the suggestion
Done
