### ISSUE TITLE
 Can you share me how to read Conceptal Caption dataset?

### ISSUE THREAD

**Issue by shoutOutYangJie** [rmokady/CLIP_prefix_caption#11]
Can you provide the dataset API.

**Comment by rmokady** [comment]
This is part of our TODO list. Hopefully, we would manage to publish it soon

**Comment by rmokady** [comment]
Hi @shoutOutYangJie 
We upload our [source code](https://github.com/rmokady/CLIP_prefix_caption/commit/ada23d906e5bde5ca7fd36c17da770f437ee64e5) for Concepual Captions, I hope you will find it useful

**Comment by shoutOutYangJie** [comment]
nice， but how to down conceptual caption dataset?





------------------ Original ------------------
From: Ron Mokady ***@***.***&gt;
Date: Wed,Dec 8,2021 2:26 AM
To: rmokady/CLIP_prefix_caption ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [rmokady/CLIP_prefix_caption]  Can you share me how to readConceptal Caption dataset? (Issue #11)





 
Hi @shoutOutYangJie
 We upload our source code for Concepual Captions, I hope you will find it useful
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rmokady** [comment]
You need to download the URL files from the [official website](https://ai.google.com/research/ConceptualCaptions/download)
And then use the script to download the images
