### ISSUE TITLE
inference for batch

### ISSUE THREAD

**Issue by trucvip123** [rmokady/CLIP_prefix_caption#12]
Can you help me inference for a batch image

**Comment by trucvip123** [comment]
i get it

**Comment by srikar2097** [comment]
Hi @trucvip123 Can you share the code to get inference for batches of images.

**Comment by baaaad** [comment]
> 

Hi, have you solved the problem of inferencing for batches of images? Single image inferencing is too slow.

**Comment by newbietuan** [comment]
> 



> Can you help me inference for a batch image

Hi,  can you share the code to get inference for batches?
Thank you very much.

**Comment by rongtongxueya** [comment]
has the same question

**Comment by szxmachinelearning** [comment]
has the same question
