### ISSUE TITLE
weight behind  clip_prefix_captioning_inference.ipynb and your demo

### ISSUE THREAD

**Issue by Cm744** [rmokady/CLIP_prefix_caption#17]
I found that both your clip_prefix_captioning_inference.ipynb and your demo https://replicate.com/rmokady/clip_prefix_caption with  worked very well for my images.
I am wondering how you got the weights behind your demo. I mean the specific hyper parameter you used to get it.
For coco mode, I ran **python train.py --data ./data/coco/oscar_split_ViT-B_32_train.pkl --out_dir ./coco_train/** with 40 batch_size and all other default arguments. I trained it for many epochs and saved many weights. However, the weights I kept didn't work as well as yours.

Could you please tell me the specific hyper parameters and arguments for the weight behind clip_prefix_captioning_inference.ipynb and your demo https://replicate.com/rmokady/clip_prefix_caption with coco model？ I will be extremely grateful!

**Comment by rmokady** [comment]
Hi @Cm744,
I can't really be sure what is the issure here
But I will try to suggest several possible solution

1. Can you make sure `only_prefix` is False? maybe the default value is not defined well in the code?
2. To save computation time, we used early stopping, If I remember we achieved good results after about 7 epochs. So maybe overfit occur for many epochs?
3. I think we used the resnet clip with the mlp
`python train.py --only_prefix --data ./data/coco/oscar_split_RN50x4_train.pkl --out_dir ./coco_train/  --is_rn`
4. You can try an earlier version of the code, such as [this](https://github.com/rmokady/CLIP_prefix_caption/tree/f431e6fc4e33bf9d09aacc0ff24e171f4037c0d4).  Maybe a bug emerged during the changes

Let me know if it was helpful
