### ISSUE TITLE
An image loss error occurred while extracting image features.

### ISSUE THREAD

**Issue by tianjunyu0871** [rmokady/CLIP_prefix_caption#21]
Thank you for sharing amazing work.  
The following problem occurred when I used parse_coke.py to extract features.  I checked the data set and did a search on the Internet and couldn't find coco_val2014_000000116100.jpg.  I hope to get your help.Thanks.
![image](https://user-images.githubusercontent.com/55222964/151654253-5fa5c71a-1bf3-41f6-8ef6-f29f2b1d6d46.png)

**Comment by rmokady** [comment]
If you skip this image, there are additional errors?
