### ISSUE TITLE
Finetuning on custom data (videos)

### ISSUE THREAD

**Issue by avinashsai** [rmokady/CLIP_prefix_caption#24]
Hi,

Congrats on the amazing project. I have a video dataset with captions. I wanted to fine-tune this model on video dataset to generate custom captions. I am planning to extract frame-wise features and concatenate them during training. Please, let me know how can I fine-tune on custom dataset.

Thanks in advance.

**Comment by rmokady** [comment]
Hi @avinashsai,
You first have to modify the parsing scripts to output the CLIP embedding for your videos

If you plan to output a caption per video (or some number of frames) it might also require some non trivial modification for the code
