### ISSUE TITLE
A question about the x dimension.

### ISSUE THREAD

**Issue by tianjunyu0871** [rmokady/CLIP_prefix_caption#26]
When I train only transformer mapping network,I found that the dimension of x is(40 , 512),but prefix_dim = 640.I don't know why this is happening. Is it caused by the extraction of clip features? Hope to get your help, thank you.  
![image](https://user-images.githubusercontent.com/55222964/153883683-be805784-803e-4190-b64a-89d4985ee840.png)

**Comment by tianjunyu0871** [comment]
Thanked your reply. 
Does the parameter is_rn represent resnet?But the following command appears is_rn?Is it a clerical error?
![image](https://user-images.githubusercontent.com/55222964/153972159-2c03173d-4a20-4a90-a1be-21232c9d651f.png)
In addition, can you share the pre-training weights of MLP and the program evaluation code?  Thank you so much!!

**Comment by rmokady** [comment]
Yes this is an error
Thank you very much for pointing it out
I will fix it ASAP

We use the evaluation code as used in the OSCAR repository
Just replacing the JSON files with our JSONs

We already shared the weights of MLP - see "Inference Notebooks" section in the readme.

**Comment by tianjunyu0871** [comment]
I tried to modify the prediction code and the following error occurred while loading the pre-trained Transformer data.
![image](https://user-images.githubusercontent.com/55222964/154673727-baaab1eb-20f2-4735-99f7-249e46d5bb94.png)
I don't know if there is a problem with my code.  Can you share your code for forecasting with Transformer?  Thank you very much!

**Comment by rmokady** [comment]
Prediction with transformer is available in [this notebook](https://github.com/rmokady/CLIP_prefix_caption/blob/main/notebooks/transformer_inference.ipynb)

**Comment by tianjunyu0871** [comment]
Thanks for your answer.May I ask why you chose gpt2 in the end? Have you tried other pre-trained gpt2 models, such as "gpt2-medium" or "gpt2-large", how is the effect?

**Comment by tianjunyu0871** [comment]
thank you for your reply.
<img width="595" alt="捕获" src="https://user-images.githubusercontent.com/55222964/155154311-afbd7298-edf6-42ec-8619-4ef711c6ee07.PNG">
I found that the type of outputs of ”outputs = model.gpt(inputs_embeds=generated)“ in generate2 is <class 'transformers.modeling_outputs.CausalLMOutputWithCrossAttentions'>
But the value of outputs.hidden_states is None, why is this, and how can I get the value of hidden_states. Looking forward to your answer, thank you!

**Comment by tianjunyu0871** [comment]
I have gained a lot from your work, but I still have a few questions, and I hope to get your answers.  
First question: I tried to remove the stoptoken, but the effect is not good, is there a good way to generate more than one sentence?  
Second question: Have you tried using different GPT models? Such as GPT2-medium or GPT2-large . Is the difference significant? 
 Third question: what does the prefix_length_clip parameter mean in training? 
 Looking forward to your reply, thank you very much!

**Comment by rmokady** [comment]
To generate more than one sentence you should replace the inference algorithm (e.g. beam search)
Using a variants of beam search you can produce different captions.

We haven't tried to use different GPT models.

prefix_length_clip control the transformer mapping network - size (in tokens) of the clip embedding, as some of the prefix is a learned const.
