### ISSUE TITLE
Question About the ClipCocoDataset in train.py

### ISSUE THREAD

**Issue by ycchanau** [rmokady/CLIP_prefix_caption#34]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/43056995/160239460-ecd3f2db-2f83-41a6-9b35-f816c0d1e8cd.png">

I have a question about the above code. I observe that in the pad_tokens function, it will save the padded token. However, if we call the pad_tokens function with the same token again,  the padded token saved where the padded part is set to 0, will be used to generate the mask with ge(0), as a result, the mask will always be one for all positions. Do I miss something?

**Comment by bofang98** [comment]
I found the same problem... The mask is correct for the 1st epoch only. And it will be all 1's for all positions after the 1st epoch.
