### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by AskingStuff** [rmokady/CLIP_prefix_caption#5]
Hello, great project :)

I wanted to try some stuff with you code, and wanted to evaluate the results with the same metrics you did on COCO or Conceptual Captions.
Is it possible for you to share the evaluation code for these metrics? And what split of the dataset did you check those against?

Thanks!

**Comment by tianjunyu0871** [comment]
> We just use the same split as used in Oscar repo
> 
> You can run their inference script which will produce a json with test captions

Could you please share your val/test captions? I'm having some difficulty running Oscar.

**Comment by rongtongxueya** [comment]
> > 我们只使用与 Oscar 存储库中使用的相同的分割
> > 您可以运行他们的推理脚本，该脚本将生成带有测试标题的 json
> 
> 您能分享您的验证/测试标题吗？我在竞选奥斯卡时遇到了一些困难。

请问您解决了吗这个我呢提，我也遇到了这个问题
