### ISSUE TITLE
Some questions about fine-tune with custom dataset

### ISSUE THREAD

**Issue by eeyrw** [rmokady/CLIP_prefix_caption#56]
I want to fine-tune the model with my custom dataset.  I have some questions:
Which pretrained model is better, COCO or Conceptual?
Is there any reference for build my custom dataset?
Whether train from scratch is better than fine-tune?

**Comment by eeyrw** [comment]
It turns out not so difficult to do.

**Comment by arminbazza** [comment]
Hey, do you mind sharing a few pointers?

**Comment by eeyrw** [comment]
1. Modify `parse_coco.py` to fit your dataset.
2. Use modified code to generate middle embedding file.
3. Train network by `train.py` with the embedding file and with arg `--only_prefix`.

**Comment by martinmclee** [comment]
> 1. Modify `parse_coco.py` to fit your dataset.
> 2. Use modified code to generate middle embedding file.
> 3. Train network by `train.py` with the embedding file and with arg `--only_prefix`.

May I know how do you load the pre-trained weights?

**Comment by rongtongxueya** [comment]
i hvae a question.I tried to use coco's json downloaded from the Internet, but it was not successful because it was different from the json marked in the code. However, I would like to know what his json file is like, why it seems that each image has only one caption

**Comment by martinmclee** [comment]
> i hvae a question.I tried to use coco's json downloaded from the Internet, but it was not successful because it was different from the json marked in the code. However, I would like to know what his json file is like, why it seems that each image has only one caption

The download link is provided [here](https://github.com/rmokady/CLIP_prefix_caption#coco-training)

**Comment by rongtongxueya** [comment]
> > 我有个问题。我尝试使用从网上下载的coco的json，但没有成功，因为它与代码中标记的json不同。不过我想知道他的json文件是什么样的，为什么好像每张图片只有一个标题
> 
> [此处](https://github.com/rmokady/CLIP_prefix_caption#coco-training)提供下载链接[](https://github.com/rmokady/CLIP_prefix_caption#coco-training)
I know, I mean I don't understand why his json is like this, I don't know how he cleans it like this, I want to try other data, but I want to clean coco's json file first and then see if it is the right way to handle it

**Comment by Junyiliu0** [comment]
i found this will out of memory
