### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cyrilzakka** [rmokady/CLIP_prefix_caption#7]
Hello,

Would you happen to have any tips for training the model? I keep on running into a `CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 15.90 GiB total capacity; 14.75 GiB already allocated; 23.75 MiB free; 14.83 GiB reserved in total by PyTorch)` problem despite training on a P-100 with 16GB of RAM. I've tried decreasing the batch size from 40 to 10 with no improvement - in fact it seems to run into a slightly different issue: `RuntimeError: CUDA out of memory. Tried to allocate 892.00 MiB (GPU 0; 15.90 GiB total capacity; 14.13 GiB already allocated; 193.75 MiB free; 14.66 GiB reserved in total by PyTorch)`. 

Setting the batch_size to 2 seems to get things running, albeit very slowly. What hardware did you train on?

**Comment by rmokady** [comment]
Hi @cyrilzakka,
We trained our model on single 1080 with 11GB memory. So It don't make sense to me.
Are you sure your GPU was completely empty when starting the training?
Do you use the same data? (COCO)
Did you keep the same GPT-2 model?
